export const treeEmployee = [
  {
    parent_key: null,
    key: "thong_tin_nhan_vien",
    title: "Thông tin nhân viên",
  },
  {
    parent_key: "thong_tin_nhan_vien",
    key: "stt",
    title: "STT",
  },
  {
    parent_key: "thong_tin_nhan_vien",
    key: "employee",
    title: "Mã nhân viên",
  },
  {
    parent_key: "thong_tin_nhan_vien",
    key: "employee_name",
    title: "Nhân viên",
  },
  {
    parent_key: "thong_tin_nhan_vien",
    key: "job_title",
    title: "Chức danh",
  },
  {
    parent_key: "thong_tin_nhan_vien",
    key: "department",
    title: "Phòng ban",
  },
]

export const treeAtt = [
    {
      parent_key: null,
      key: "cong_tong",
      title: "Công tổng",
    },
    {
      parent_key: "cong_tong",
      key: "number_of_hours_monthly",
      title: "Số giờ",
    },
    {
      parent_key: "cong_tong",
      key: "work_hours_monthly",
      title: "Số công",
    },
    {
      parent_key: null,
      key: "tong_hop_di_muon",
      title: "Tổng hợp đi muộn",
    },
    {
      parent_key: "tong_hop_di_muon",
      key: "late_arrival_time_monthly",
      title: "Số phút",
    },
    {
      parent_key: "tong_hop_di_muon",
      key: "number_of_late_arrival",
      title: "Số lần",
    },
    {
      parent_key: "tong_hop_di_muon",
      key: "late_arrival_work_monthly",
      title: "Công muộn",
    },
    {
      parent_key: null,
      key: "tong_hop_ve_som",
      title: "Tổng hợp về sớm",
    },
    {
      parent_key: "tong_hop_ve_som",
      key: "early_arrival_time_monthly",
      title: "Số phút",
    },
    {
      parent_key: "tong_hop_ve_som",
      key: "number_of_early_arrival",
      title: "Số lần",
    },
    {
      parent_key: "tong_hop_ve_som",
      key: "early_arrival_work_monthly",
      title: "Công muộn",
    },
    {
      parent_key: null,
      key: "tong_hop_vang_mat",
      title: "Tổng hợp vắng mặt",
    },
    {
      parent_key: "tong_hop_vang_mat",
      key: "number_hour_absent_monthly",
      title: "Số phút",
    },
    {
      parent_key: "tong_hop_vang_mat",
      key: "number_absent",
      title: "Số lần",
    },
    {
      parent_key: "tong_hop_vang_mat",
      key: "number_work_absent_monthly",
      title: "Công sớm",
    },
    {
      parent_key: "tong_hop_vang_mat",
      key: "number_of_breaktime",
      title: "Quên chốt",
    },
    {
      parent_key: null,
      key: "tong_hop_nghi_khong_ly_do",
      title: "Tổng hợp nghỉ không lý do",
    },
    {
      parent_key: "tong_hop_nghi_khong_ly_do",
      key: "number_work_unexplain_absence_monthly",
      title: "Số công",
    },
    {
      parent_key: null,
      key: "tong_hop_nghi_ly_do",
      title: "Tổng hợp nghỉ lý do",
    },
    {
      parent_key: "tong_hop_nghi_ly_do",
      key: "number_work_explain_absence_monthly",
      title: "Tổng công (P-Công,KL-Công,...)",
    },
    {
parent_key: "tong_hop_nghi_ly_do",
      key: "number_hour_explain_absence_monthly",
      title: "Tổng giờ (P-Giờ, KL-Giờ,...)",
    },
    {
      parent_key: null,
      key: "tong_hop_nghi_cong_chinh",
      title: "Tổng hợp Công chính",
    },
    {
      parent_key: "tong_hop_nghi_cong_chinh",
      key: "number_work_shift_monthly",
      title: "Công ca (Tổng hợp Công chuẩn-Công chuẩn)",
    },
    {
      parent_key: "tong_hop_nghi_cong_chinh",
      key: "number_of_holiday_monthly",
      title: "Công lễ",
    },
    {
      parent_key: "tong_hop_nghi_cong_chinh",
      key: "work_of_mission_monthly",
      title: "Công tác",
    },
    {
      parent_key: null,
      key: "tong_hop_lam_them",
      title: "Tổng hợp làm thêm",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_off_monthly",
      title: "Giờ nghỉ",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_off_day_monthly",
      title: "Nghỉ ngày",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_off_night_monthly",
      title: "Nghỉ đêm",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_holiday_monthly",
      title: "Giờ lễ",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_holiday_day_monthly",
      title: "Lễ ngày",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_holiday_night_monthly",
      title: "Lễ đêm",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_monthly",
      title: "Giờ ngày",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_day_monthly",
      title: "Ngày",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hour_night_monthly",
      title: "Đêm",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "extra_hours_monthly",
      title: "Tổng giờ",
    },
    {
      parent_key: "tong_hop_lam_them",
      key: "number_of_extra_hour",
      title: "Số lần",
    },
    {
      parent_key: null,
      key: "tong_hop_tang_ca",
      title: "Tổng hợp tăng ca",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_hour_off_monthly",
      title: "Giờ nghỉ",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_hour_holiday_monthly",
      title: "Giờ lễ",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_hours_monthly",
      title: "Giờ ngày",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_hour_total",
      title: "Tổng giờ",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_work_off_monthly",
      title: "Công nghỉ",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_work_holiday_monthly",
      title: "Công lễ",
    },
    {
      parent_key: "tong_hop_tang_ca",
key: "overtime_works_monthly",
      title: "Công ngày",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_works_total",
      title: "Số công",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "overtime_works_extract",
      title: "Công chuẩn",
    },
    {
      parent_key: "tong_hop_tang_ca",
      key: "number_of_overtime",
      title: "Số lần",
    },
    {
      parent_key: null,
      key: "tong_hop_qua_ngay",
      title: "Tổng hợp qua ngày",
    },
    {
      parent_key: "tong_hop_qua_ngay",
      key: "throughout_hour_monthly",
      title: "Số giờ",
    },
    {
      parent_key: "tong_hop_qua_ngay",
      key: "throughout_work_monthly",
      title: "Số công",
    },
    {
      parent_key: "tong_hop_qua_ngay",
      key: "throughout_work_extract_monthly",
      title: "Công thực tế",
    },
    {
      parent_key: "tong_hop_qua_ngay",
      key: "throughout_hour_extract_monthly",
      title: "Giờ thực tế",
    },
    {
      parent_key: "tong_hop_qua_ngay",
      key: "throughout_number",
      title: "Số lần",
    },
    {
      parent_key: null,
      key: "tong_hop_HC_CS",
      title: "Tổng hợp HC, CS,...(Dữ liệu chấm công theo từng ca làm việc)",
    },
    {
      parent_key: "tong_hop_HC_CS",
      key: "hc_work_monthly",
      title: "Số công",
    },
    {
      parent_key: "tong_hop_HC_CS",
      key: "hc_hour_monthly",
      title: "Số giờ",
    },
    {
      parent_key: "tong_hop_HC_CS",
      key: "hc_work_extract_monthly",
      title: "Công thực tế",
    },
    {
      parent_key: "tong_hop_HC_CS",
      key: "hc_hour_extract_monthly",
      title: "Giờ thực tế",
    },
    {
      parent_key: "tong_hop_HC_CS",
      key: "hc_number",
      title: "Số lần",
    },
    {
      parent_key: null,
      key: "tong_hop_lam_viec_ngay_le",
      title: "Tổng hợp làm việc ngày lễ",
    },
    {
      parent_key: "tong_hop_lam_viec_ngay_le",
      key: "number_work_holiday_monthly",
      title: "Số công",
    },
    {
      parent_key: "tong_hop_lam_viec_ngay_le",
      key: "number_hour_holiday_monthly",
      title: "Số giờ",
    },
    {
      parent_key: null,
      key: "tong_hop_ngay_cham_cong",
      title: "Tổng hợp ngày chấm công",
    },
    {
      parent_key: "tong_hop_ngay_cham_cong",
      key: "number_of_day_work",
      title: "Số ngày",
    },
  ];

export const notHide = [
'thong_tin_nhan_vien',
 'stt',
 'employee',
 'employee_name'
]

export const fixedLeft = [
  'stt', 
  'employee', 
  'employee_name', 
  'job_title', 
  'department', 
  ]

export const defaultColumn = [
'thong_tin_nhan_vien', 
'stt', 
'employee', 
'employee_name', 
'job_title', 
'department', 
'cong_tong', 
'number_of_hours_monthly', 
'work_hours_monthly', 
'tong_hop_di_muon', 
'late_arrival_time_monthly', 
'number_of_late_arrival', 
'late_arrival_work_monthly', 
'tong_hop_ve_som', 
'early_arrival_time_monthly', 
'number_of_early_arrival', 
'early_arrival_work_monthly', 
'tong_hop_vang_mat', 
'number_hour_absent_monthly', 
'number_absent', 
'number_work_absent_monthly', 
'number_of_breaktime', 
'tong_hop_nghi_khong_ly_do', 
'number_work_unexplain_absence_monthly', 
'tong_hop_nghi_ly_do', 
'number_work_explain_absence_monthly', 
'number_hour_explain_absence_monthly', 
'tong_hop_nghi_cong_chinh', 
'number_work_shift_monthly', 
'number_of_holiday_monthly', 
'work_of_mission_monthly', 
'tong_hop_lam_them', 
'extra_hour_off_monthly', 
'extra_hour_off_day_monthly', 
'extra_hour_off_night_monthly', 
'extra_hour_holiday_monthly', 
'extra_hour_holiday_day_monthly', 
'extra_hour_holiday_night_monthly', 
'extra_hour_monthly', 
'extra_hour_day_monthly', 
'extra_hour_night_monthly', 
'extra_hours_monthly', 
'number_of_extra_hour', 
'tong_hop_tang_ca', 
'overtime_hour_off_monthly', 
'overtime_hour_holiday_monthly', 
'overtime_hours_monthly', 
'overtime_hour_total', 
'overtime_work_off_monthly', 
'overtime_work_holiday_monthly', 
'overtime_works_monthly', 
'overtime_works_total', 
'overtime_works_extract', 
'number_of_overtime', 
'tong_hop_qua_ngay', 
'throughout_hour_monthly', 
'throughout_work_monthly', 
'throughout_work_extract_monthly', 
'throughout_hour_extract_monthly', 
'throughout_number', 
'tong_hop_HC_CS', 
'hc_work_monthly', 
'hc_hour_monthly', 
'hc_work_extract_monthly', 
'hc_hour_extract_monthly', 
'hc_number', 
'tong_hop_lam_viec_ngay_le', 
'number_work_holiday_monthly', 
'number_hour_holiday_monthly', 
'tong_hop_ngay_cham_cong', 
'number_of_day_work']